### ISSUE TITLE
Could you please specify the license for your software in this toolbox?

### ISSUE THREAD

**Issue by ramayer** [nfriend/toolbox#1]
I have a need for something extremely similar to your  Smart Date Searching for Solr class: 

https://nathanfriend.io/2017/06/26/smart-date-searching-with-solr.html

If released under an Apache 2 (like solr) or compatible license, or public domain, I'd just fork and slightly modify yours.  Otherwise, I'll probably need to write something similar.

**Comment by nfriend** [comment]
Yep, no problem! I added a LICENSE file that licenses this repo under the MIT license.
